package com.lixiang.ssm.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.lixiang.ssm.entity.LoanApplication;

public interface LoanApplicationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loan_application
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loan_application
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    int insert(LoanApplication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loan_application
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    int insertSelective(LoanApplication record);

    /**
     * 通过申请结果查询申请列表
     * @param result 结果：0=未处理，1=申请未通过，2=通过申请
     * @return
     */
    List<LoanApplication> listSelectByResult(@Param("result")int result);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loan_application
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    int updateByPrimaryKeySelective(LoanApplication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loan_application
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    int updateByPrimaryKey(LoanApplication record);
}