package com.lixiang.ssm.dao;

import com.lixiang.ssm.entity.LoanApplication;

public interface LoanApplicationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loan_application
     *
     * @mbg.generated Wed May 16 11:32:23 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loan_application
     *
     * @mbg.generated Wed May 16 11:32:23 CST 2018
     */
    int insert(LoanApplication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loan_application
     *
     * @mbg.generated Wed May 16 11:32:23 CST 2018
     */
    int insertSelective(LoanApplication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loan_application
     *
     * @mbg.generated Wed May 16 11:32:23 CST 2018
     */
    LoanApplication selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loan_application
     *
     * @mbg.generated Wed May 16 11:32:23 CST 2018
     */
    int updateByPrimaryKeySelective(LoanApplication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loan_application
     *
     * @mbg.generated Wed May 16 11:32:23 CST 2018
     */
    int updateByPrimaryKey(LoanApplication record);
}