package com.lixiang.ssm.dao;

import com.lixiang.ssm.entity.PaybackPlan;

public interface PaybackPlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payback_plan
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payback_plan
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    int insert(PaybackPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payback_plan
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    int insertSelective(PaybackPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payback_plan
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    PaybackPlan selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payback_plan
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    int updateByPrimaryKeySelective(PaybackPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payback_plan
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    int updateByPrimaryKey(PaybackPlan record);
}