package com.lixiang.ssm.dao;

import com.lixiang.ssm.entity.PlatFormAccount;

public interface PlatFormAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_platform_account
     *
     * @mbg.generated Wed May 16 11:21:31 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_platform_account
     *
     * @mbg.generated Wed May 16 11:21:31 CST 2018
     */
    int insert(PlatFormAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_platform_account
     *
     * @mbg.generated Wed May 16 11:21:31 CST 2018
     */
    int insertSelective(PlatFormAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_platform_account
     *
     * @mbg.generated Wed May 16 11:21:31 CST 2018
     */
    PlatFormAccount selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_platform_account
     *
     * @mbg.generated Wed May 16 11:21:31 CST 2018
     */
    int updateByPrimaryKeySelective(PlatFormAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_platform_account
     *
     * @mbg.generated Wed May 16 11:21:31 CST 2018
     */
    int updateByPrimaryKey(PlatFormAccount record);
}