package com.lixiang.ssm.dao;


import com.lixiang.ssm.entity.Product;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Tue May 08 17:27:53 CST 2018
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Tue May 08 17:27:53 CST 2018
     */
    int insertSelective(Product record);
    
    boolean decrStock(Integer id);
}
