package com.lixiang.ssm.dao;

import com.lixiang.ssm.entity.ProjectFile;

public interface ProjectFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_file
     *
     * @mbg.generated Wed May 16 11:21:31 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_file
     *
     * @mbg.generated Wed May 16 11:21:31 CST 2018
     */
    int insert(ProjectFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_file
     *
     * @mbg.generated Wed May 16 11:21:31 CST 2018
     */
    int insertSelective(ProjectFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_file
     *
     * @mbg.generated Wed May 16 11:21:31 CST 2018
     */
    ProjectFile selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_file
     *
     * @mbg.generated Wed May 16 11:21:31 CST 2018
     */
    int updateByPrimaryKeySelective(ProjectFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_file
     *
     * @mbg.generated Wed May 16 11:21:31 CST 2018
     */
    int updateByPrimaryKey(ProjectFile record);
}