package com.lixiang.ssm.dao;

import com.lixiang.ssm.entity.Redpacket;

public interface RedpacketMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_redpacket
     *
     * @mbg.generated Wed May 16 11:21:31 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_redpacket
     *
     * @mbg.generated Wed May 16 11:21:31 CST 2018
     */
    int insert(Redpacket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_redpacket
     *
     * @mbg.generated Wed May 16 11:21:31 CST 2018
     */
    int insertSelective(Redpacket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_redpacket
     *
     * @mbg.generated Wed May 16 11:21:31 CST 2018
     */
    Redpacket selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_redpacket
     *
     * @mbg.generated Wed May 16 11:21:31 CST 2018
     */
    int updateByPrimaryKeySelective(Redpacket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_redpacket
     *
     * @mbg.generated Wed May 16 11:21:31 CST 2018
     */
    int updateByPrimaryKey(Redpacket record);
}