package com.lixiang.ssm.dao;

import com.lixiang.ssm.entity.RepaymentPlan;

public interface RepaymentPlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_repayment_plan
     *
     * @mbg.generated Wed May 16 12:22:04 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_repayment_plan
     *
     * @mbg.generated Wed May 16 12:22:04 CST 2018
     */
    int insert(RepaymentPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_repayment_plan
     *
     * @mbg.generated Wed May 16 12:22:04 CST 2018
     */
    int insertSelective(RepaymentPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_repayment_plan
     *
     * @mbg.generated Wed May 16 12:22:04 CST 2018
     */
    RepaymentPlan selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_repayment_plan
     *
     * @mbg.generated Wed May 16 12:22:04 CST 2018
     */
    int updateByPrimaryKeySelective(RepaymentPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_repayment_plan
     *
     * @mbg.generated Wed May 16 12:22:04 CST 2018
     */
    int updateByPrimaryKey(RepaymentPlan record);
}