package com.lixiang.ssm.dao;

import java.util.List;

import com.lixiang.ssm.entity.Resources;

public interface ResourcesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    int insert(Resources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    int insertSelective(Resources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    /**
     * 根据ID查询
     * @param id
     * @return
     */
    Resources selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    int updateByPrimaryKeySelective(Resources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    int updateByPrimaryKey(Resources record);
    
    /**
     * 拦截
     * @param record
     * @return
     */
    List<Resources> getAllResource();
    /**
     * 查询全部
     * @param record
     * @return
     */
    List<Resources> queryAllResource(Resources record);
}