package com.lixiang.ssm.dao;

import java.util.List;
import java.util.Set;

import org.apache.ibatis.annotations.Param;

import com.lixiang.ssm.entity.Resources;
import com.lixiang.ssm.entity.Role;

public interface RoleMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table role
	 *
	 * @mbg.generated Thu May 03 17:07:31 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table role
	 *
	 * @mbg.generated Thu May 03 17:07:31 CST 2018
	 */
	int insert(Role record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table role
	 *
	 * @mbg.generated Thu May 03 17:07:31 CST 2018
	 */
	boolean insertSelective(Role record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table role
	 *
	 * @mbg.generated Thu May 03 17:07:31 CST 2018
	 */
	Role selectByPrimaryKey(Integer id);
	
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table role
	 *
	 * @mbg.generated Thu May 03 17:07:31 CST 2018
	 */
	boolean updateByPrimaryKeySelective(Role record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table role
	 *
	 * @mbg.generated Thu May 03 17:07:31 CST 2018
	 */
	int updateByPrimaryKey(Role record);

	Set<String> getRoleByUserName(String username);
	
	Set<String> getRoleNameByUserId(Integer username);

	Set<String> getPermsByUserName(String username);

	List<Role> getRolesForUsername(String username);

	List<Role> getRolesForUserId(Integer id);
	
	List<Role> getAllRoles();
	
	List<Resources> getResForRoleId(Integer id);
	boolean deleteRoleByUserId(int userId);
	boolean deleteResByRoleId(int roleId);
	boolean deleteRoleByRoleId(int roleId);
	
	boolean batchAddRole(@Param("userId") int userId,@Param("roleIds") int[] roleIds);
	
	boolean batchAddRes(@Param("roleId") int roleId,@Param("resIds") int[] resIds);
	
	List<Role> listRoles(Role role);
    List<Role> getRolesList();
    
    List<Role> list(Role role);
    
    
   
  
    
}