package com.lixiang.ssm.dao;

import com.lixiang.ssm.entity.SystemMessage;

public interface SystemMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_message
     *
     * @mbg.generated Wed May 16 11:21:21 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_message
     *
     * @mbg.generated Wed May 16 11:21:21 CST 2018
     */
    int insert(SystemMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_message
     *
     * @mbg.generated Wed May 16 11:21:21 CST 2018
     */
    int insertSelective(SystemMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_message
     *
     * @mbg.generated Wed May 16 11:21:21 CST 2018
     */
    SystemMessage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_message
     *
     * @mbg.generated Wed May 16 11:21:21 CST 2018
     */
    int updateByPrimaryKeySelective(SystemMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_message
     *
     * @mbg.generated Wed May 16 11:21:21 CST 2018
     */
    int updateByPrimaryKey(SystemMessage record);
}