package com.lixiang.ssm.dao;

import java.util.List;

import com.lixiang.ssm.entity.TraRecord;

public interface TraRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tra_record
     *
     * @mbg.generated Wed May 16 11:21:21 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tra_record
     *
     * @mbg.generated Wed May 16 11:21:21 CST 2018
     */
    int insert(TraRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tra_record
     *
     * @mbg.generated Wed May 16 11:21:21 CST 2018
     */
    int insertSelective(TraRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tra_record
     *
     * @mbg.generated Wed May 16 11:21:21 CST 2018
     */
    TraRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tra_record
     *
     * @mbg.generated Wed May 16 11:21:21 CST 2018
     */
    int updateByPrimaryKeySelective(TraRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tra_record
     *
     * @mbg.generated Wed May 16 11:21:21 CST 2018
     */
    int updateByPrimaryKey(TraRecord record);
    
    /**
     * 资金记录
     * @param fraRecord
     * @return
     */
    List<TraRecord> selectFundRecord(TraRecord traRecord);
}