package com.lixiang.ssm.dao;

import com.lixiang.ssm.entity.UserCredit;

public interface UserCreditMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_credit
     *
     * @mbg.generated Wed May 16 11:18:32 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_credit
     *
     * @mbg.generated Wed May 16 11:18:32 CST 2018
     */
    int insert(UserCredit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_credit
     *
     * @mbg.generated Wed May 16 11:18:32 CST 2018
     */
    int insertSelective(UserCredit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_credit
     *
     * @mbg.generated Wed May 16 11:18:32 CST 2018
     */
    UserCredit selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_credit
     *
     * @mbg.generated Wed May 16 11:18:32 CST 2018
     */
    int updateByPrimaryKeySelective(UserCredit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_credit
     *
     * @mbg.generated Wed May 16 11:18:32 CST 2018
     */
    int updateByPrimaryKey(UserCredit record);
}