package com.lixiang.ssm.dao;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.lixiang.ssm.entity.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    int insert(User record);

    
    Integer selectCount();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    int updateByPrimaryKey(User record);
    
    
    User getUserByName(String name);
    
    boolean updateErrorCountByUser(@Param("username") String username,@Param("errorCount")  int errorCount,@Param("loginDate") Date loginDate);
    
    List<User> list(User user);
    boolean delUserByPrimaryKey(Integer id);

	boolean delUserGroupByPrimaryKey(Integer id);

	boolean delUserRoleByPrimaryKey(Integer id);
    boolean unlockUser(Integer id);
    

    List<User>  getUserName(String user);
    

}