package com.lixiang.ssm.entity;

import java.util.Date;

import javax.validation.constraints.Future;
import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Past;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

public class LoanApplication {
    //申请单的id,大于1的数字
	@Min(1)
    private Integer id;

    //申请人的id,大于1的数字
    @Min(1)
    private Integer userId;

    //申请人的真实姓名,2-15个字符,不能为空
	@Length(min=2,max=15)
	@NotEmpty
    private String realName;

    //申请人的联系电话,最长20位,不能为空
	@Length(max=20)
	@NotEmpty
    private String contactNumber;

    //借款金额,最低10000，最高1999990000
	@Min(10000)
	@Max(1999990000)
    private Integer loanBalance;

    //借款期限,最低1个月，最高999个月
	@Min(1)
	@Max(999)
    private Integer loanTerm;

    //申请人所在地址,最长30位
	@Length(max=30)
	@NotEmpty
    private String address;

	//结果：0=未处理，1=申请未通过，2=通过申请
	@Min(0)
	@Max(2)
    private Integer result;

	//申请时间
	@Past
    private Date appliyDate;

	//处理人ID,大于1的数字
	@Min(1)
    private Integer handlerId;

    //处理姓名
    @NotEmpty
    private String handlerName;

    //处理时间
    @Past
    private Date handlerDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loan_application
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    public LoanApplication(Integer id, Integer userId, String realName, String contactNumber, Integer loanBalance, Integer loanTerm, String address, Integer result, Date appliyDate, Integer handlerId, String handlerName, Date handlerDate) {
        this.id = id;
        this.userId = userId;
        this.realName = realName;
        this.contactNumber = contactNumber;
        this.loanBalance = loanBalance;
        this.loanTerm = loanTerm;
        this.address = address;
        this.result = result;
        this.appliyDate = appliyDate;
        this.handlerId = handlerId;
        this.handlerName = handlerName;
        this.handlerDate = handlerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loan_application
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    public LoanApplication() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loan_application.id
     *
     * @return the value of t_loan_application.id
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loan_application.id
     *
     * @param id the value for t_loan_application.id
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loan_application.user_id
     *
     * @return the value of t_loan_application.user_id
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loan_application.user_id
     *
     * @param userId the value for t_loan_application.user_id
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loan_application.real_name
     *
     * @return the value of t_loan_application.real_name
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loan_application.real_name
     *
     * @param realName the value for t_loan_application.real_name
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loan_application.contact_number
     *
     * @return the value of t_loan_application.contact_number
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    public String getContactNumber() {
        return contactNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loan_application.contact_number
     *
     * @param contactNumber the value for t_loan_application.contact_number
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    public void setContactNumber(String contactNumber) {
        this.contactNumber = contactNumber == null ? null : contactNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loan_application.loan_balance
     *
     * @return the value of t_loan_application.loan_balance
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    public Integer getLoanBalance() {
        return loanBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loan_application.loan_balance
     *
     * @param loanBalance the value for t_loan_application.loan_balance
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    public void setLoanBalance(Integer loanBalance) {
        this.loanBalance = loanBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loan_application.loan_term
     *
     * @return the value of t_loan_application.loan_term
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    public Integer getLoanTerm() {
        return loanTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loan_application.loan_term
     *
     * @param loanTerm the value for t_loan_application.loan_term
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    public void setLoanTerm(Integer loanTerm) {
        this.loanTerm = loanTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loan_application.address
     *
     * @return the value of t_loan_application.address
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loan_application.address
     *
     * @param address the value for t_loan_application.address
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loan_application.result
     *
     * @return the value of t_loan_application.result
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    public Integer getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loan_application.result
     *
     * @param result the value for t_loan_application.result
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    public void setResult(Integer result) {
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loan_application.appliy_date
     *
     * @return the value of t_loan_application.appliy_date
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    public Date getAppliyDate() {
        return appliyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loan_application.appliy_date
     *
     * @param appliyDate the value for t_loan_application.appliy_date
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    public void setAppliyDate(Date appliyDate) {
        this.appliyDate = appliyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loan_application.handler_id
     *
     * @return the value of t_loan_application.handler_id
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    public Integer getHandlerId() {
        return handlerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loan_application.handler_id
     *
     * @param handlerId the value for t_loan_application.handler_id
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    public void setHandlerId(Integer handlerId) {
        this.handlerId = handlerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loan_application.handler_name
     *
     * @return the value of t_loan_application.handler_name
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    public String getHandlerName() {
        return handlerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loan_application.handler_name
     *
     * @param handlerName the value for t_loan_application.handler_name
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    public void setHandlerName(String handlerName) {
        this.handlerName = handlerName == null ? null : handlerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loan_application.handler_date
     *
     * @return the value of t_loan_application.handler_date
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    public Date getHandlerDate() {
        return handlerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loan_application.handler_date
     *
     * @param handlerDate the value for t_loan_application.handler_date
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    public void setHandlerDate(Date handlerDate) {
        this.handlerDate = handlerDate;
    }

	@Override
	public String toString()
	{
		return "LoanApplication [id=" + id + ", userId=" + userId + ", realName=" + realName + ", contactNumber="
				+ contactNumber + ", loanBalance=" + loanBalance + ", loanTerm=" + loanTerm + ", address=" + address
				+ ", result=" + result + ", appliyDate=" + appliyDate + ", handlerId=" + handlerId + ", handlerName="
				+ handlerName + ", handlerDate=" + handlerDate + "]";
	}
    
    
}