package com.lixiang.ssm.entity;

import java.util.Date;

public class LoanApplication {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loan_application.id
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loan_application.user_id
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loan_application.real_name
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loan_application.contact_number
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    private String contactNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loan_application.loan_balance
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    private Integer loanBalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loan_application.loan_term
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    private Integer loanTerm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loan_application.address
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loan_application.result
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    private Integer result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loan_application.appliy_date
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    private Date appliyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loan_application.handler_id
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    private Integer handlerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loan_application.handler_name
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    private String handlerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loan_application.handler_date
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    private Date handlerDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loan_application
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    public LoanApplication(Integer id, Integer userId, String realName, String contactNumber, Integer loanBalance, Integer loanTerm, String address, Integer result, Date appliyDate, Integer handlerId, String handlerName, Date handlerDate) {
        this.id = id;
        this.userId = userId;
        this.realName = realName;
        this.contactNumber = contactNumber;
        this.loanBalance = loanBalance;
        this.loanTerm = loanTerm;
        this.address = address;
        this.result = result;
        this.appliyDate = appliyDate;
        this.handlerId = handlerId;
        this.handlerName = handlerName;
        this.handlerDate = handlerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loan_application
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    public LoanApplication() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loan_application.id
     *
     * @return the value of t_loan_application.id
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loan_application.id
     *
     * @param id the value for t_loan_application.id
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loan_application.user_id
     *
     * @return the value of t_loan_application.user_id
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loan_application.user_id
     *
     * @param userId the value for t_loan_application.user_id
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loan_application.real_name
     *
     * @return the value of t_loan_application.real_name
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loan_application.real_name
     *
     * @param realName the value for t_loan_application.real_name
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loan_application.contact_number
     *
     * @return the value of t_loan_application.contact_number
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    public String getContactNumber() {
        return contactNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loan_application.contact_number
     *
     * @param contactNumber the value for t_loan_application.contact_number
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    public void setContactNumber(String contactNumber) {
        this.contactNumber = contactNumber == null ? null : contactNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loan_application.loan_balance
     *
     * @return the value of t_loan_application.loan_balance
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    public Integer getLoanBalance() {
        return loanBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loan_application.loan_balance
     *
     * @param loanBalance the value for t_loan_application.loan_balance
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    public void setLoanBalance(Integer loanBalance) {
        this.loanBalance = loanBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loan_application.loan_term
     *
     * @return the value of t_loan_application.loan_term
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    public Integer getLoanTerm() {
        return loanTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loan_application.loan_term
     *
     * @param loanTerm the value for t_loan_application.loan_term
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    public void setLoanTerm(Integer loanTerm) {
        this.loanTerm = loanTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loan_application.address
     *
     * @return the value of t_loan_application.address
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loan_application.address
     *
     * @param address the value for t_loan_application.address
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loan_application.result
     *
     * @return the value of t_loan_application.result
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    public Integer getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loan_application.result
     *
     * @param result the value for t_loan_application.result
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    public void setResult(Integer result) {
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loan_application.appliy_date
     *
     * @return the value of t_loan_application.appliy_date
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    public Date getAppliyDate() {
        return appliyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loan_application.appliy_date
     *
     * @param appliyDate the value for t_loan_application.appliy_date
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    public void setAppliyDate(Date appliyDate) {
        this.appliyDate = appliyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loan_application.handler_id
     *
     * @return the value of t_loan_application.handler_id
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    public Integer getHandlerId() {
        return handlerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loan_application.handler_id
     *
     * @param handlerId the value for t_loan_application.handler_id
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    public void setHandlerId(Integer handlerId) {
        this.handlerId = handlerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loan_application.handler_name
     *
     * @return the value of t_loan_application.handler_name
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    public String getHandlerName() {
        return handlerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loan_application.handler_name
     *
     * @param handlerName the value for t_loan_application.handler_name
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    public void setHandlerName(String handlerName) {
        this.handlerName = handlerName == null ? null : handlerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loan_application.handler_date
     *
     * @return the value of t_loan_application.handler_date
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    public Date getHandlerDate() {
        return handlerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loan_application.handler_date
     *
     * @param handlerDate the value for t_loan_application.handler_date
     *
     * @mbg.generated Wed May 16 12:04:37 CST 2018
     */
    public void setHandlerDate(Date handlerDate) {
        this.handlerDate = handlerDate;
    }
}