package com.lixiang.ssm.entity;

import java.math.BigDecimal;
import java.util.Date;

public class LoanProject extends BaseEntity {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_loan_project.id
	 *
	 * @mbg.generated Wed May 16 12:22:04 CST 2018
	 */
	private Integer id;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_loan_project.project_name
	 *
	 * @mbg.generated Wed May 16 12:22:04 CST 2018
	 */
	private String projectName;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_loan_project.project_no
	 *
	 * @mbg.generated Wed May 16 12:22:04 CST 2018
	 */
	private Integer projectNo;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_loan_project.loan_user_id
	 *
	 * @mbg.generated Wed May 16 12:22:04 CST 2018
	 */
	private Integer loanUserId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_loan_project.loan_user_name
	 *
	 * @mbg.generated Wed May 16 12:22:04 CST 2018
	 */
	private String loanUserName;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_loan_project.loan_balance
	 *
	 * @mbg.generated Wed May 16 12:22:04 CST 2018
	 */
	private Integer loanBalance;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_loan_project.annual_rate
	 *
	 * @mbg.generated Wed May 16 12:22:04 CST 2018
	 */
	private BigDecimal annualRate;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_loan_project.loan_term
	 *
	 * @mbg.generated Wed May 16 12:22:04 CST 2018
	 */
	private Integer loanTerm;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_loan_project.repayment_method
	 *
	 * @mbg.generated Wed May 16 12:22:04 CST 2018
	 */
	private Integer repaymentMethod;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_loan_project.loan_reason
	 *
	 * @mbg.generated Wed May 16 12:22:04 CST 2018
	 */
	private String loanReason;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_loan_project.borrower_info
	 *
	 * @mbg.generated Wed May 16 12:22:04 CST 2018
	 */
	private String borrowerInfo;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_loan_project.risk_control
	 *
	 * @mbg.generated Wed May 16 12:22:04 CST 2018
	 */
	private String riskControl;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_loan_project.project_status
	 *
	 * @mbg.generated Wed May 16 12:22:04 CST 2018
	 */
	private Integer projectStatus;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_loan_project.creator_id
	 *
	 * @mbg.generated Wed May 16 12:22:04 CST 2018
	 */
	private Integer creatorId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_loan_project.creator_name
	 *
	 * @mbg.generated Wed May 16 12:22:04 CST 2018
	 */
	private String creatorName;

	private Date creatorDate;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_loan_project.modifior_id
	 *
	 * @mbg.generated Wed May 16 12:22:04 CST 2018
	 */
	private Integer modifiorId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_loan_project.modifior_name
	 *
	 * @mbg.generated Wed May 16 12:22:04 CST 2018
	 */
	private String modifiorName;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_loan_project.modify_date
	 *
	 * @mbg.generated Wed May 16 12:22:04 CST 2018
	 */
	private Date modifyDate;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_loan_project
	 *
	 * @mbg.generated Wed May 16 12:22:04 CST 2018
	 */
	public LoanProject(Integer id, String projectName, Integer projectNo, Integer loanUserId, String loanUserName,
			Integer loanBalance, BigDecimal annualRate, Integer loanTerm, Integer repaymentMethod, String loanReason,
			String borrowerInfo, String riskControl, Integer projectStatus, Integer creatorId, String creatorName,Date creatorDate,
			Integer modifiorId, String modifiorName, Date modifyDate) {
		this.id = id;
		this.projectName = projectName;
		this.projectNo = projectNo;
		this.loanUserId = loanUserId;
		this.loanUserName = loanUserName;
		this.loanBalance = loanBalance;
		this.annualRate = annualRate;
		this.loanTerm = loanTerm;
		this.repaymentMethod = repaymentMethod;
		this.loanReason = loanReason;
		this.borrowerInfo = borrowerInfo;
		this.riskControl = riskControl;
		this.projectStatus = projectStatus;
		this.creatorId = creatorId;
		this.creatorName = creatorName;
		this.creatorDate=creatorDate;
		this.modifiorId = modifiorId;
		this.modifiorName = modifiorName;
		this.modifyDate = modifyDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_loan_project
	 *
	 * @mbg.generated Wed May 16 12:22:04 CST 2018
	 */
	public LoanProject() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_loan_project.id
	 *
	 * @return the value of t_loan_project.id
	 *
	 * @mbg.generated Wed May 16 12:22:04 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_loan_project.id
	 *
	 * @param id
	 *            the value for t_loan_project.id
	 *
	 * @mbg.generated Wed May 16 12:22:04 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_loan_project.project_name
	 *
	 * @return the value of t_loan_project.project_name
	 *
	 * @mbg.generated Wed May 16 12:22:04 CST 2018
	 */
	public String getProjectName() {
		return projectName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_loan_project.project_name
	 *
	 * @param projectName
	 *            the value for t_loan_project.project_name
	 *
	 * @mbg.generated Wed May 16 12:22:04 CST 2018
	 */
	public void setProjectName(String projectName) {
		this.projectName = projectName == null ? null : projectName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_loan_project.project_no
	 *
	 * @return the value of t_loan_project.project_no
	 *
	 * @mbg.generated Wed May 16 12:22:04 CST 2018
	 */
	public Integer getProjectNo() {
		return projectNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_loan_project.project_no
	 *
	 * @param projectNo
	 *            the value for t_loan_project.project_no
	 *
	 * @mbg.generated Wed May 16 12:22:04 CST 2018
	 */
	public void setProjectNo(Integer projectNo) {
		this.projectNo = projectNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_loan_project.loan_user_id
	 *
	 * @return the value of t_loan_project.loan_user_id
	 *
	 * @mbg.generated Wed May 16 12:22:04 CST 2018
	 */
	public Integer getLoanUserId() {
		return loanUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_loan_project.loan_user_id
	 *
	 * @param loanUserId
	 *            the value for t_loan_project.loan_user_id
	 *
	 * @mbg.generated Wed May 16 12:22:04 CST 2018
	 */
	public void setLoanUserId(Integer loanUserId) {
		this.loanUserId = loanUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_loan_project.loan_user_name
	 *
	 * @return the value of t_loan_project.loan_user_name
	 *
	 * @mbg.generated Wed May 16 12:22:04 CST 2018
	 */
	public String getLoanUserName() {
		return loanUserName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_loan_project.loan_user_name
	 *
	 * @param loanUserName
	 *            the value for t_loan_project.loan_user_name
	 *
	 * @mbg.generated Wed May 16 12:22:04 CST 2018
	 */
	public void setLoanUserName(String loanUserName) {
		this.loanUserName = loanUserName == null ? null : loanUserName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_loan_project.loan_balance
	 *
	 * @return the value of t_loan_project.loan_balance
	 *
	 * @mbg.generated Wed May 16 12:22:04 CST 2018
	 */
	public Integer getLoanBalance() {
		return loanBalance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_loan_project.loan_balance
	 *
	 * @param loanBalance
	 *            the value for t_loan_project.loan_balance
	 *
	 * @mbg.generated Wed May 16 12:22:04 CST 2018
	 */
	public void setLoanBalance(Integer loanBalance) {
		this.loanBalance = loanBalance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_loan_project.annual_rate
	 *
	 * @return the value of t_loan_project.annual_rate
	 *
	 * @mbg.generated Wed May 16 12:22:04 CST 2018
	 */
	public BigDecimal getAnnualRate() {
		return annualRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_loan_project.annual_rate
	 *
	 * @param annualRate
	 *            the value for t_loan_project.annual_rate
	 *
	 * @mbg.generated Wed May 16 12:22:04 CST 2018
	 */
	public void setAnnualRate(BigDecimal annualRate) {
		this.annualRate = annualRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_loan_project.loan_term
	 *
	 * @return the value of t_loan_project.loan_term
	 *
	 * @mbg.generated Wed May 16 12:22:04 CST 2018
	 */
	public Integer getLoanTerm() {
		return loanTerm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_loan_project.loan_term
	 *
	 * @param loanTerm
	 *            the value for t_loan_project.loan_term
	 *
	 * @mbg.generated Wed May 16 12:22:04 CST 2018
	 */
	public void setLoanTerm(Integer loanTerm) {
		this.loanTerm = loanTerm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_loan_project.repayment_method
	 *
	 * @return the value of t_loan_project.repayment_method
	 *
	 * @mbg.generated Wed May 16 12:22:04 CST 2018
	 */
	public Integer getRepaymentMethod() {
		return repaymentMethod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_loan_project.repayment_method
	 *
	 * @param repaymentMethod
	 *            the value for t_loan_project.repayment_method
	 *
	 * @mbg.generated Wed May 16 12:22:04 CST 2018
	 */
	public void setRepaymentMethod(Integer repaymentMethod) {
		this.repaymentMethod = repaymentMethod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_loan_project.loan_reason
	 *
	 * @return the value of t_loan_project.loan_reason
	 *
	 * @mbg.generated Wed May 16 12:22:04 CST 2018
	 */
	public String getLoanReason() {
		return loanReason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_loan_project.loan_reason
	 *
	 * @param loanReason
	 *            the value for t_loan_project.loan_reason
	 *
	 * @mbg.generated Wed May 16 12:22:04 CST 2018
	 */
	public void setLoanReason(String loanReason) {
		this.loanReason = loanReason == null ? null : loanReason.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_loan_project.borrower_info
	 *
	 * @return the value of t_loan_project.borrower_info
	 *
	 * @mbg.generated Wed May 16 12:22:04 CST 2018
	 */
	public String getBorrowerInfo() {
		return borrowerInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_loan_project.borrower_info
	 *
	 * @param borrowerInfo
	 *            the value for t_loan_project.borrower_info
	 *
	 * @mbg.generated Wed May 16 12:22:04 CST 2018
	 */
	public void setBorrowerInfo(String borrowerInfo) {
		this.borrowerInfo = borrowerInfo == null ? null : borrowerInfo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_loan_project.risk_control
	 *
	 * @return the value of t_loan_project.risk_control
	 *
	 * @mbg.generated Wed May 16 12:22:04 CST 2018
	 */
	public String getRiskControl() {
		return riskControl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_loan_project.risk_control
	 *
	 * @param riskControl
	 *            the value for t_loan_project.risk_control
	 *
	 * @mbg.generated Wed May 16 12:22:04 CST 2018
	 */
	public void setRiskControl(String riskControl) {
		this.riskControl = riskControl == null ? null : riskControl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_loan_project.project_status
	 *
	 * @return the value of t_loan_project.project_status
	 *
	 * @mbg.generated Wed May 16 12:22:04 CST 2018
	 */
	public Integer getProjectStatus() {
		return projectStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_loan_project.project_status
	 *
	 * @param projectStatus
	 *            the value for t_loan_project.project_status
	 *
	 * @mbg.generated Wed May 16 12:22:04 CST 2018
	 */
	public void setProjectStatus(Integer projectStatus) {
		this.projectStatus = projectStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_loan_project.creator_id
	 *
	 * @return the value of t_loan_project.creator_id
	 *
	 * @mbg.generated Wed May 16 12:22:04 CST 2018
	 */
	public Integer getCreatorId() {
		return creatorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_loan_project.creator_id
	 *
	 * @param creatorId
	 *            the value for t_loan_project.creator_id
	 *
	 * @mbg.generated Wed May 16 12:22:04 CST 2018
	 */
	public void setCreatorId(Integer creatorId) {
		this.creatorId = creatorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_loan_project.creator_name
	 *
	 * @return the value of t_loan_project.creator_name
	 *
	 * @mbg.generated Wed May 16 12:22:04 CST 2018
	 */
	public String getCreatorName() {
		return creatorName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_loan_project.creator_name
	 *
	 * @param creatorName
	 *            the value for t_loan_project.creator_name
	 *
	 * @mbg.generated Wed May 16 12:22:04 CST 2018
	 */
	public void setCreatorName(String creatorName) {
		this.creatorName = creatorName == null ? null : creatorName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_loan_project.modifior_id
	 *
	 * @return the value of t_loan_project.modifior_id
	 *
	 * @mbg.generated Wed May 16 12:22:04 CST 2018
	 */
	public Integer getModifiorId() {
		return modifiorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_loan_project.modifior_id
	 *
	 * @param modifiorId
	 *            the value for t_loan_project.modifior_id
	 *
	 * @mbg.generated Wed May 16 12:22:04 CST 2018
	 */
	public void setModifiorId(Integer modifiorId) {
		this.modifiorId = modifiorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_loan_project.modifior_name
	 *
	 * @return the value of t_loan_project.modifior_name
	 *
	 * @mbg.generated Wed May 16 12:22:04 CST 2018
	 */
	public String getModifiorName() {
		return modifiorName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_loan_project.modifior_name
	 *
	 * @param modifiorName
	 *            the value for t_loan_project.modifior_name
	 *
	 * @mbg.generated Wed May 16 12:22:04 CST 2018
	 */
	public void setModifiorName(String modifiorName) {
		this.modifiorName = modifiorName == null ? null : modifiorName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_loan_project.modify_date
	 *
	 * @return the value of t_loan_project.modify_date
	 *
	 * @mbg.generated Wed May 16 12:22:04 CST 2018
	 */
	public Date getModifyDate() {
		return modifyDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_loan_project.modify_date
	 *
	 * @param modifyDate
	 *            the value for t_loan_project.modify_date
	 *
	 * @mbg.generated Wed May 16 12:22:04 CST 2018
	 */
	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	public Date getCreatorDate() {
		return creatorDate;
	}

	public void setCreatorDate(Date date) {
		this.creatorDate = date;
	}

	@Override
	public String toString() {
		return "LoanProject [id=" + id + ", projectName=" + projectName + ", projectNo=" + projectNo + ", loanUserId="
				+ loanUserId + ", loanUserName=" + loanUserName + ", loanBalance=" + loanBalance + ", annualRate="
				+ annualRate + ", loanTerm=" + loanTerm + ", repaymentMethod=" + repaymentMethod + ", loanReason="
				+ loanReason + ", borrowerInfo=" + borrowerInfo + ", riskControl=" + riskControl + ", projectStatus="
				+ projectStatus + ", creatorId=" + creatorId + ", creatorName=" + creatorName + ", creatorDate="
				+ creatorDate + ", modifiorId=" + modifiorId + ", modifiorName=" + modifiorName + ", modifyDate="
				+ modifyDate + "]";
	}

}