package com.lixiang.ssm.entity;

import java.io.Serializable;
import java.util.Arrays;
import java.util.Date;

public class News implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 145896605307179626L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.id
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.title
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.classify
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    private Boolean classify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.read_number
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    private Integer readNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.status
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.creator_id
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    private Integer creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.creator_name
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    private String creatorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.create_date
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.publish_date
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    private Date publishDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.publisher_id
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    private Integer publisherId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.publisher_name
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    private String publisherName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.content
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    private byte[] content;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    public News(Integer id, String title, Boolean classify, Integer readNumber, Boolean status, Integer creatorId, String creatorName, Date createDate, Date publishDate, Integer publisherId, String publisherName, byte[] content) {
        this.id = id;
        this.title = title;
        this.classify = classify;
        this.readNumber = readNumber;
        this.status = status;
        this.creatorId = creatorId;
        this.creatorName = creatorName;
        this.createDate = createDate;
        this.publishDate = publishDate;
        this.publisherId = publisherId;
        this.publisherName = publisherName;
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    public News() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.id
     *
     * @return the value of t_news.id
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.id
     *
     * @param id the value for t_news.id
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.title
     *
     * @return the value of t_news.title
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.title
     *
     * @param title the value for t_news.title
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.classify
     *
     * @return the value of t_news.classify
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    public Boolean getClassify() {
        return classify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.classify
     *
     * @param classify the value for t_news.classify
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    public void setClassify(Boolean classify) {
        this.classify = classify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.read_number
     *
     * @return the value of t_news.read_number
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    public Integer getReadNumber() {
        return readNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.read_number
     *
     * @param readNumber the value for t_news.read_number
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    public void setReadNumber(Integer readNumber) {
        this.readNumber = readNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.status
     *
     * @return the value of t_news.status
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.status
     *
     * @param status the value for t_news.status
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.creator_id
     *
     * @return the value of t_news.creator_id
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.creator_id
     *
     * @param creatorId the value for t_news.creator_id
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.creator_name
     *
     * @return the value of t_news.creator_name
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.creator_name
     *
     * @param creatorName the value for t_news.creator_name
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName == null ? null : creatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.create_date
     *
     * @return the value of t_news.create_date
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.create_date
     *
     * @param createDate the value for t_news.create_date
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.publish_date
     *
     * @return the value of t_news.publish_date
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    public Date getPublishDate() {
        return publishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.publish_date
     *
     * @param publishDate the value for t_news.publish_date
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    public void setPublishDate(Date publishDate) {
        this.publishDate = publishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.publisher_id
     *
     * @return the value of t_news.publisher_id
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    public Integer getPublisherId() {
        return publisherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.publisher_id
     *
     * @param publisherId the value for t_news.publisher_id
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    public void setPublisherId(Integer publisherId) {
        this.publisherId = publisherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.publisher_name
     *
     * @return the value of t_news.publisher_name
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    public String getPublisherName() {
        return publisherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.publisher_name
     *
     * @param publisherName the value for t_news.publisher_name
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    public void setPublisherName(String publisherName) {
        this.publisherName = publisherName == null ? null : publisherName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.content
     *
     * @return the value of t_news.content
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    public byte[] getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.content
     *
     * @param content the value for t_news.content
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    public void setContent(byte[] content) {
        this.content = content;
    }

	@Override
	public String toString() {
		return "News [id=" + id + ", title=" + title + ", classify=" + classify + ", readNumber=" + readNumber
				+ ", status=" + status + ", creatorId=" + creatorId + ", creatorName=" + creatorName + ", createDate="
				+ createDate + ", publishDate=" + publishDate + ", publisherId=" + publisherId + ", publisherName="
				+ publisherName + ", content=" + Arrays.toString(content) + "]";
	}
    
    
}