package com.lixiang.ssm.entity;

import java.math.BigDecimal;
import java.util.Date;

public class PaybackPlan {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_payback_plan.id
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_payback_plan.inv_record_id
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    private Integer invRecordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_payback_plan.project_id
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    private Integer projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_payback_plan.project_name
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    private String projectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_payback_plan.payback_no
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    private Integer paybackNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_payback_plan.plan_payback_date
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    private Date planPaybackDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_payback_plan.payback_date
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    private Date paybackDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_payback_plan.payback_status
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    private Integer paybackStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_payback_plan.payback_money
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    private BigDecimal paybackMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_payback_plan.payback_margin
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    private BigDecimal paybackMargin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_payback_plan.operator_id
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    private Integer operatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_payback_plan.operator_name
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    private String operatorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_payback_plan.operator_date
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    private Date operatorDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payback_plan
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    public PaybackPlan(Integer id, Integer invRecordId, Integer projectId, String projectName, Integer paybackNo, Date planPaybackDate, Date paybackDate, Integer paybackStatus, BigDecimal paybackMoney, BigDecimal paybackMargin, Integer operatorId, String operatorName, Date operatorDate) {
        this.id = id;
        this.invRecordId = invRecordId;
        this.projectId = projectId;
        this.projectName = projectName;
        this.paybackNo = paybackNo;
        this.planPaybackDate = planPaybackDate;
        this.paybackDate = paybackDate;
        this.paybackStatus = paybackStatus;
        this.paybackMoney = paybackMoney;
        this.paybackMargin = paybackMargin;
        this.operatorId = operatorId;
        this.operatorName = operatorName;
        this.operatorDate = operatorDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payback_plan
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    public PaybackPlan() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_payback_plan.id
     *
     * @return the value of t_payback_plan.id
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_payback_plan.id
     *
     * @param id the value for t_payback_plan.id
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_payback_plan.inv_record_id
     *
     * @return the value of t_payback_plan.inv_record_id
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    public Integer getInvRecordId() {
        return invRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_payback_plan.inv_record_id
     *
     * @param invRecordId the value for t_payback_plan.inv_record_id
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    public void setInvRecordId(Integer invRecordId) {
        this.invRecordId = invRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_payback_plan.project_id
     *
     * @return the value of t_payback_plan.project_id
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_payback_plan.project_id
     *
     * @param projectId the value for t_payback_plan.project_id
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_payback_plan.project_name
     *
     * @return the value of t_payback_plan.project_name
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_payback_plan.project_name
     *
     * @param projectName the value for t_payback_plan.project_name
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_payback_plan.payback_no
     *
     * @return the value of t_payback_plan.payback_no
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    public Integer getPaybackNo() {
        return paybackNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_payback_plan.payback_no
     *
     * @param paybackNo the value for t_payback_plan.payback_no
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    public void setPaybackNo(Integer paybackNo) {
        this.paybackNo = paybackNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_payback_plan.plan_payback_date
     *
     * @return the value of t_payback_plan.plan_payback_date
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    public Date getPlanPaybackDate() {
        return planPaybackDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_payback_plan.plan_payback_date
     *
     * @param planPaybackDate the value for t_payback_plan.plan_payback_date
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    public void setPlanPaybackDate(Date planPaybackDate) {
        this.planPaybackDate = planPaybackDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_payback_plan.payback_date
     *
     * @return the value of t_payback_plan.payback_date
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    public Date getPaybackDate() {
        return paybackDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_payback_plan.payback_date
     *
     * @param paybackDate the value for t_payback_plan.payback_date
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    public void setPaybackDate(Date paybackDate) {
        this.paybackDate = paybackDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_payback_plan.payback_status
     *
     * @return the value of t_payback_plan.payback_status
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    public Integer getPaybackStatus() {
        return paybackStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_payback_plan.payback_status
     *
     * @param paybackStatus the value for t_payback_plan.payback_status
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    public void setPaybackStatus(Integer paybackStatus) {
        this.paybackStatus = paybackStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_payback_plan.payback_money
     *
     * @return the value of t_payback_plan.payback_money
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    public BigDecimal getPaybackMoney() {
        return paybackMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_payback_plan.payback_money
     *
     * @param paybackMoney the value for t_payback_plan.payback_money
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    public void setPaybackMoney(BigDecimal paybackMoney) {
        this.paybackMoney = paybackMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_payback_plan.payback_margin
     *
     * @return the value of t_payback_plan.payback_margin
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    public BigDecimal getPaybackMargin() {
        return paybackMargin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_payback_plan.payback_margin
     *
     * @param paybackMargin the value for t_payback_plan.payback_margin
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    public void setPaybackMargin(BigDecimal paybackMargin) {
        this.paybackMargin = paybackMargin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_payback_plan.operator_id
     *
     * @return the value of t_payback_plan.operator_id
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    public Integer getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_payback_plan.operator_id
     *
     * @param operatorId the value for t_payback_plan.operator_id
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    public void setOperatorId(Integer operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_payback_plan.operator_name
     *
     * @return the value of t_payback_plan.operator_name
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    public String getOperatorName() {
        return operatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_payback_plan.operator_name
     *
     * @param operatorName the value for t_payback_plan.operator_name
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName == null ? null : operatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_payback_plan.operator_date
     *
     * @return the value of t_payback_plan.operator_date
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    public Date getOperatorDate() {
        return operatorDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_payback_plan.operator_date
     *
     * @param operatorDate the value for t_payback_plan.operator_date
     *
     * @mbg.generated Wed May 16 11:53:23 CST 2018
     */
    public void setOperatorDate(Date operatorDate) {
        this.operatorDate = operatorDate;
    }
    
    
}