package com.lixiang.ssm.entity;

import java.math.BigDecimal;
import java.util.Date;

public class PlatFormAccount {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_platform_account.id
     *
     * @mbg.generated Wed May 16 11:21:31 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_platform_account.money_tra_type
     *
     * @mbg.generated Wed May 16 11:21:31 CST 2018
     */
    private Integer moneyTraType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_platform_account.money_tra_money
     *
     * @mbg.generated Wed May 16 11:21:31 CST 2018
     */
    private BigDecimal moneyTraMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_platform_account.money_tra_date
     *
     * @mbg.generated Wed May 16 11:21:31 CST 2018
     */
    private Date moneyTraDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_platform_account.remark
     *
     * @mbg.generated Wed May 16 11:21:31 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_platform_account
     *
     * @mbg.generated Wed May 16 11:21:31 CST 2018
     */
    public PlatFormAccount(Integer id, Integer moneyTraType, BigDecimal moneyTraMoney, Date moneyTraDate, String remark) {
        this.id = id;
        this.moneyTraType = moneyTraType;
        this.moneyTraMoney = moneyTraMoney;
        this.moneyTraDate = moneyTraDate;
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_platform_account
     *
     * @mbg.generated Wed May 16 11:21:31 CST 2018
     */
    public PlatFormAccount() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_platform_account.id
     *
     * @return the value of t_platform_account.id
     *
     * @mbg.generated Wed May 16 11:21:31 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_platform_account.id
     *
     * @param id the value for t_platform_account.id
     *
     * @mbg.generated Wed May 16 11:21:31 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_platform_account.money_tra_type
     *
     * @return the value of t_platform_account.money_tra_type
     *
     * @mbg.generated Wed May 16 11:21:31 CST 2018
     */
    public Integer getMoneyTraType() {
        return moneyTraType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_platform_account.money_tra_type
     *
     * @param moneyTraType the value for t_platform_account.money_tra_type
     *
     * @mbg.generated Wed May 16 11:21:31 CST 2018
     */
    public void setMoneyTraType(Integer moneyTraType) {
        this.moneyTraType = moneyTraType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_platform_account.money_tra_money
     *
     * @return the value of t_platform_account.money_tra_money
     *
     * @mbg.generated Wed May 16 11:21:31 CST 2018
     */
    public BigDecimal getMoneyTraMoney() {
        return moneyTraMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_platform_account.money_tra_money
     *
     * @param moneyTraMoney the value for t_platform_account.money_tra_money
     *
     * @mbg.generated Wed May 16 11:21:31 CST 2018
     */
    public void setMoneyTraMoney(BigDecimal moneyTraMoney) {
        this.moneyTraMoney = moneyTraMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_platform_account.money_tra_date
     *
     * @return the value of t_platform_account.money_tra_date
     *
     * @mbg.generated Wed May 16 11:21:31 CST 2018
     */
    public Date getMoneyTraDate() {
        return moneyTraDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_platform_account.money_tra_date
     *
     * @param moneyTraDate the value for t_platform_account.money_tra_date
     *
     * @mbg.generated Wed May 16 11:21:31 CST 2018
     */
    public void setMoneyTraDate(Date moneyTraDate) {
        this.moneyTraDate = moneyTraDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_platform_account.remark
     *
     * @return the value of t_platform_account.remark
     *
     * @mbg.generated Wed May 16 11:21:31 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_platform_account.remark
     *
     * @param remark the value for t_platform_account.remark
     *
     * @mbg.generated Wed May 16 11:21:31 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}