package com.lixiang.ssm.entity;

import java.math.BigDecimal;
import java.util.Date;

public class RepaymentPlan {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_repayment_plan.id
     *
     * @mbg.generated Wed May 16 12:22:04 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_repayment_plan.project_id
     *
     * @mbg.generated Wed May 16 12:22:04 CST 2018
     */
    private Integer projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_repayment_plan.project_name
     *
     * @mbg.generated Wed May 16 12:22:04 CST 2018
     */
    private String projectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_repayment_plan.repayment_no
     *
     * @mbg.generated Wed May 16 12:22:04 CST 2018
     */
    private Integer repaymentNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_repayment_plan.plan_repayment_time
     *
     * @mbg.generated Wed May 16 12:22:04 CST 2018
     */
    private Date planRepaymentTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_repayment_plan.repayment_time
     *
     * @mbg.generated Wed May 16 12:22:04 CST 2018
     */
    private Date repaymentTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_repayment_plan.interest
     *
     * @mbg.generated Wed May 16 12:22:04 CST 2018
     */
    private BigDecimal interest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_repayment_plan.principle
     *
     * @mbg.generated Wed May 16 12:22:04 CST 2018
     */
    private BigDecimal principle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_repayment_plan.status
     *
     * @mbg.generated Wed May 16 12:22:04 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_repayment_plan.operator_id
     *
     * @mbg.generated Wed May 16 12:22:04 CST 2018
     */
    private Integer operatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_repayment_plan.operator_name
     *
     * @mbg.generated Wed May 16 12:22:04 CST 2018
     */
    private String operatorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_repayment_plan.operator_date
     *
     * @mbg.generated Wed May 16 12:22:04 CST 2018
     */
    private Date operatorDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_repayment_plan
     *
     * @mbg.generated Wed May 16 12:22:04 CST 2018
     */
    public RepaymentPlan(Integer id, Integer projectId, String projectName, Integer repaymentNo, Date planRepaymentTime, Date repaymentTime, BigDecimal interest, BigDecimal principle, Integer status, Integer operatorId, String operatorName, Date operatorDate) {
        this.id = id;
        this.projectId = projectId;
        this.projectName = projectName;
        this.repaymentNo = repaymentNo;
        this.planRepaymentTime = planRepaymentTime;
        this.repaymentTime = repaymentTime;
        this.interest = interest;
        this.principle = principle;
        this.status = status;
        this.operatorId = operatorId;
        this.operatorName = operatorName;
        this.operatorDate = operatorDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_repayment_plan
     *
     * @mbg.generated Wed May 16 12:22:04 CST 2018
     */
    public RepaymentPlan() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_repayment_plan.id
     *
     * @return the value of t_repayment_plan.id
     *
     * @mbg.generated Wed May 16 12:22:04 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_repayment_plan.id
     *
     * @param id the value for t_repayment_plan.id
     *
     * @mbg.generated Wed May 16 12:22:04 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_repayment_plan.project_id
     *
     * @return the value of t_repayment_plan.project_id
     *
     * @mbg.generated Wed May 16 12:22:04 CST 2018
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_repayment_plan.project_id
     *
     * @param projectId the value for t_repayment_plan.project_id
     *
     * @mbg.generated Wed May 16 12:22:04 CST 2018
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_repayment_plan.project_name
     *
     * @return the value of t_repayment_plan.project_name
     *
     * @mbg.generated Wed May 16 12:22:04 CST 2018
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_repayment_plan.project_name
     *
     * @param projectName the value for t_repayment_plan.project_name
     *
     * @mbg.generated Wed May 16 12:22:04 CST 2018
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_repayment_plan.repayment_no
     *
     * @return the value of t_repayment_plan.repayment_no
     *
     * @mbg.generated Wed May 16 12:22:04 CST 2018
     */
    public Integer getRepaymentNo() {
        return repaymentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_repayment_plan.repayment_no
     *
     * @param repaymentNo the value for t_repayment_plan.repayment_no
     *
     * @mbg.generated Wed May 16 12:22:04 CST 2018
     */
    public void setRepaymentNo(Integer repaymentNo) {
        this.repaymentNo = repaymentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_repayment_plan.plan_repayment_time
     *
     * @return the value of t_repayment_plan.plan_repayment_time
     *
     * @mbg.generated Wed May 16 12:22:04 CST 2018
     */
    public Date getPlanRepaymentTime() {
        return planRepaymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_repayment_plan.plan_repayment_time
     *
     * @param planRepaymentTime the value for t_repayment_plan.plan_repayment_time
     *
     * @mbg.generated Wed May 16 12:22:04 CST 2018
     */
    public void setPlanRepaymentTime(Date planRepaymentTime) {
        this.planRepaymentTime = planRepaymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_repayment_plan.repayment_time
     *
     * @return the value of t_repayment_plan.repayment_time
     *
     * @mbg.generated Wed May 16 12:22:04 CST 2018
     */
    public Date getRepaymentTime() {
        return repaymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_repayment_plan.repayment_time
     *
     * @param repaymentTime the value for t_repayment_plan.repayment_time
     *
     * @mbg.generated Wed May 16 12:22:04 CST 2018
     */
    public void setRepaymentTime(Date repaymentTime) {
        this.repaymentTime = repaymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_repayment_plan.interest
     *
     * @return the value of t_repayment_plan.interest
     *
     * @mbg.generated Wed May 16 12:22:04 CST 2018
     */
    public BigDecimal getInterest() {
        return interest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_repayment_plan.interest
     *
     * @param interest the value for t_repayment_plan.interest
     *
     * @mbg.generated Wed May 16 12:22:04 CST 2018
     */
    public void setInterest(BigDecimal interest) {
        this.interest = interest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_repayment_plan.principle
     *
     * @return the value of t_repayment_plan.principle
     *
     * @mbg.generated Wed May 16 12:22:04 CST 2018
     */
    public BigDecimal getPrinciple() {
        return principle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_repayment_plan.principle
     *
     * @param principle the value for t_repayment_plan.principle
     *
     * @mbg.generated Wed May 16 12:22:04 CST 2018
     */
    public void setPrinciple(BigDecimal principle) {
        this.principle = principle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_repayment_plan.status
     *
     * @return the value of t_repayment_plan.status
     *
     * @mbg.generated Wed May 16 12:22:04 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_repayment_plan.status
     *
     * @param status the value for t_repayment_plan.status
     *
     * @mbg.generated Wed May 16 12:22:04 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_repayment_plan.operator_id
     *
     * @return the value of t_repayment_plan.operator_id
     *
     * @mbg.generated Wed May 16 12:22:04 CST 2018
     */
    public Integer getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_repayment_plan.operator_id
     *
     * @param operatorId the value for t_repayment_plan.operator_id
     *
     * @mbg.generated Wed May 16 12:22:04 CST 2018
     */
    public void setOperatorId(Integer operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_repayment_plan.operator_name
     *
     * @return the value of t_repayment_plan.operator_name
     *
     * @mbg.generated Wed May 16 12:22:04 CST 2018
     */
    public String getOperatorName() {
        return operatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_repayment_plan.operator_name
     *
     * @param operatorName the value for t_repayment_plan.operator_name
     *
     * @mbg.generated Wed May 16 12:22:04 CST 2018
     */
    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName == null ? null : operatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_repayment_plan.operator_date
     *
     * @return the value of t_repayment_plan.operator_date
     *
     * @mbg.generated Wed May 16 12:22:04 CST 2018
     */
    public Date getOperatorDate() {
        return operatorDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_repayment_plan.operator_date
     *
     * @param operatorDate the value for t_repayment_plan.operator_date
     *
     * @mbg.generated Wed May 16 12:22:04 CST 2018
     */
    public void setOperatorDate(Date operatorDate) {
        this.operatorDate = operatorDate;
    }
}