package com.lixiang.ssm.entity;

import java.util.Date;

import org.hibernate.validator.constraints.NotEmpty;

public class Resources extends BaseEntity{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources.id
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources.res_name
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    @NotEmpty
    private String resName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources.res_url
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    private String resUrl;
    
    
    private String myresource;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources.auth
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    private String auth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources.res_desc
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    private String resDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources.creator_id
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    private Integer creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources.create_date
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources.modifior_id
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    private Integer modifiorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources.modify_date
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    private Date modifyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources.sort
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources.type
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    public Resources(Integer id, String resName, String resUrl, String auth, String resDesc, Integer creatorId, Date createDate, Integer modifiorId, Date modifyDate, Integer sort, Integer type) {
        this.id = id;
        this.resName = resName;
        this.resUrl = resUrl;
        this.auth = auth;
        this.resDesc = resDesc;
        this.creatorId = creatorId;
        this.createDate = createDate;
        this.modifiorId = modifiorId;
        this.modifyDate = modifyDate;
        this.sort = sort;
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    public Resources() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources.id
     *
     * @return the value of resources.id
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources.id
     *
     * @param id the value for resources.id
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources.res_name
     *
     * @return the value of resources.res_name
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    public String getResName() {
        return resName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources.res_name
     *
     * @param resName the value for resources.res_name
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    public void setResName(String resName) {
        this.resName = resName == null ? null : resName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources.res_url
     *
     * @return the value of resources.res_url
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    public String getResUrl() {
        return resUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources.res_url
     *
     * @param resUrl the value for resources.res_url
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    public void setResUrl(String resUrl) {
        this.resUrl = resUrl == null ? null : resUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources.auth
     *
     * @return the value of resources.auth
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    public String getAuth() {
        return auth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources.auth
     *
     * @param auth the value for resources.auth
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    public void setAuth(String auth) {
        this.auth = auth == null ? null : auth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources.res_desc
     *
     * @return the value of resources.res_desc
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    public String getResDesc() {
        return resDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources.res_desc
     *
     * @param resDesc the value for resources.res_desc
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    public void setResDesc(String resDesc) {
        this.resDesc = resDesc == null ? null : resDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources.creator_id
     *
     * @return the value of resources.creator_id
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources.creator_id
     *
     * @param creatorId the value for resources.creator_id
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources.create_date
     *
     * @return the value of resources.create_date
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources.create_date
     *
     * @param createDate the value for resources.create_date
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources.modifior_id
     *
     * @return the value of resources.modifior_id
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    public Integer getModifiorId() {
        return modifiorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources.modifior_id
     *
     * @param modifiorId the value for resources.modifior_id
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    public void setModifiorId(Integer modifiorId) {
        this.modifiorId = modifiorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources.modify_date
     *
     * @return the value of resources.modify_date
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources.modify_date
     *
     * @param modifyDate the value for resources.modify_date
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources.sort
     *
     * @return the value of resources.sort
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources.sort
     *
     * @param sort the value for resources.sort
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources.type
     *
     * @return the value of resources.type
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources.type
     *
     * @param type the value for resources.type
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

	public String getMyresource() {
		return myresource;
	}

	public void setMyresource(String myresource) {
		this.myresource = myresource;
	}


}