package com.lixiang.ssm.entity;

import java.util.Date;

public class Role extends BaseEntity{
    /**
	 * 
	 */

	private static final long serialVersionUID = 1L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.id
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_name
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    private String roleName;

    
    private String myrole;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_desc
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    private String roleDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.creator_id
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    private Integer creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.creator_date
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    private Date creatorDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.modifior_id
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    private Integer modifiorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.modify_date
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    private Date modifyDate;
    
    //是否是用户组的角色
    private boolean isgrouprole;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    public Role(Integer id, String roleName, String roleDesc, Integer creatorId, Date creatorDate, Integer modifiorId, Date modifyDate) {
        this.id = id;
        this.roleName = roleName;
        this.roleDesc = roleDesc;
        this.creatorId = creatorId;
        this.creatorDate = creatorDate;
        this.modifiorId = modifiorId;
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    public Role() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.id
     *
     * @return the value of role.id
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.id
     *
     * @param id the value for role.id
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_name
     *
     * @return the value of role.role_name
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_name
     *
     * @param roleName the value for role.role_name
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_desc
     *
     * @return the value of role.role_desc
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    public String getRoleDesc() {
        return roleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_desc
     *
     * @param roleDesc the value for role.role_desc
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    public void setRoleDesc(String roleDesc) {
        this.roleDesc = roleDesc == null ? null : roleDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.creator_id
     *
     * @return the value of role.creator_id
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.creator_id
     *
     * @param creatorId the value for role.creator_id
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.creator_date
     *
     * @return the value of role.creator_date
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    public Date getCreatorDate() {
        return creatorDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.creator_date
     *
     * @param creatorDate the value for role.creator_date
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    public void setCreatorDate(Date creatorDate) {
        this.creatorDate = creatorDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.modifior_id
     *
     * @return the value of role.modifior_id
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    public Integer getModifiorId() {
        return modifiorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.modifior_id
     *
     * @param modifiorId the value for role.modifior_id
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    public void setModifiorId(Integer modifiorId) {
        this.modifiorId = modifiorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.modify_date
     *
     * @return the value of role.modify_date
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.modify_date
     *
     * @param modifyDate the value for role.modify_date
     *
     * @mbg.generated Thu May 03 17:07:31 CST 2018
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

	public String getMyrole() {
		return myrole;
	}

	public void setMyrole(String myrole) {
		this.myrole = myrole;
	}

	public boolean isIsgrouprole()
	{
		return isgrouprole;
	}

	public void setIsgrouprole(boolean isgrouprole)
	{
		this.isgrouprole = isgrouprole;
	}
	
	
    
    
    
}