package com.lixiang.ssm.entity;

import java.util.Date;

public class UserCredit {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_credit.id
     *
     * @mbg.generated Wed May 16 11:18:32 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_credit.user_id
     *
     * @mbg.generated Wed May 16 11:18:32 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_credit.credit_level
     *
     * @mbg.generated Wed May 16 11:18:32 CST 2018
     */
    private String creditLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_credit.credit_info
     *
     * @mbg.generated Wed May 16 11:18:32 CST 2018
     */
    private String creditInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_credit.create_date
     *
     * @mbg.generated Wed May 16 11:18:32 CST 2018
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_credit
     *
     * @mbg.generated Wed May 16 11:18:32 CST 2018
     */
    public UserCredit(Integer id, Integer userId, String creditLevel, String creditInfo, Date createDate) {
        this.id = id;
        this.userId = userId;
        this.creditLevel = creditLevel;
        this.creditInfo = creditInfo;
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_credit
     *
     * @mbg.generated Wed May 16 11:18:32 CST 2018
     */
    public UserCredit() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_credit.id
     *
     * @return the value of t_user_credit.id
     *
     * @mbg.generated Wed May 16 11:18:32 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_credit.id
     *
     * @param id the value for t_user_credit.id
     *
     * @mbg.generated Wed May 16 11:18:32 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_credit.user_id
     *
     * @return the value of t_user_credit.user_id
     *
     * @mbg.generated Wed May 16 11:18:32 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_credit.user_id
     *
     * @param userId the value for t_user_credit.user_id
     *
     * @mbg.generated Wed May 16 11:18:32 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_credit.credit_level
     *
     * @return the value of t_user_credit.credit_level
     *
     * @mbg.generated Wed May 16 11:18:32 CST 2018
     */
    public String getCreditLevel() {
        return creditLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_credit.credit_level
     *
     * @param creditLevel the value for t_user_credit.credit_level
     *
     * @mbg.generated Wed May 16 11:18:32 CST 2018
     */
    public void setCreditLevel(String creditLevel) {
        this.creditLevel = creditLevel == null ? null : creditLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_credit.credit_info
     *
     * @return the value of t_user_credit.credit_info
     *
     * @mbg.generated Wed May 16 11:18:32 CST 2018
     */
    public String getCreditInfo() {
        return creditInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_credit.credit_info
     *
     * @param creditInfo the value for t_user_credit.credit_info
     *
     * @mbg.generated Wed May 16 11:18:32 CST 2018
     */
    public void setCreditInfo(String creditInfo) {
        this.creditInfo = creditInfo == null ? null : creditInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_credit.create_date
     *
     * @return the value of t_user_credit.create_date
     *
     * @mbg.generated Wed May 16 11:18:32 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_credit.create_date
     *
     * @param createDate the value for t_user_credit.create_date
     *
     * @mbg.generated Wed May 16 11:18:32 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}